# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-21 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockid', models.CharField(max_length=30, verbose_name='\u4ea7\u54c1ID')),
                ('stockname', models.CharField(max_length=30, verbose_name='\u4ea7\u54c1\u540d\u79f0')),
                ('stockprice', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='\u5f53\u524d\u4ef7\u683c')),
            ],
        ),
    ]
