# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-21 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stockid',
            field=models.CharField(max_length=30, unique=True, verbose_name='\u4ea7\u54c1ID'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stockname',
            field=models.CharField(max_length=30, unique=True, verbose_name='\u4ea7\u54c1\u540d\u79f0'),
        ),
    ]
