# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-17 19:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sale', '0001_initial'),
        ('teacher', '0001_initial'),
        ('wxqq', '0001_initial'),
        ('bursar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u59d3\u540d')),
                ('phone', models.CharField(max_length=30, null=True, verbose_name='\u7535\u8bdd')),
                ('wxid', models.CharField(default='', max_length=30, null=True, verbose_name='\u5fae\u4fe1\u53f7')),
                ('wxname', models.CharField(default='', max_length=30, null=True, verbose_name='\u5fae\u4fe1\u6635\u79f0')),
                ('qqid', models.CharField(default='', max_length=30, null=True, verbose_name='QQ')),
                ('qqname', models.CharField(default='', max_length=30, null=True, verbose_name='QQ\u6635\u79f0')),
                ('startup', models.IntegerField(default=0, verbose_name='\u521d\u59cb\u8d44\u91d1')),
                ('gem', models.BooleanField(default=False, verbose_name='\u521b\u4e1a\u677f')),
                ('crude', models.BooleanField(default=False, verbose_name='\u539f\u6cb910W+')),
                ('spotStatus', models.CharField(default='\u672a\u5f00\u53d1', max_length=5, verbose_name='\u73b0\u8d27\u5ba2\u6237\u72b6\u6001')),
                ('spotTime', models.DateTimeField(null=True, verbose_name='\u73b0\u8d27\u8f93\u9001\u65f6\u95f4')),
                ('spotDay', models.IntegerField(null=True, verbose_name='\u5f00\u53d1\u5468\u671f')),
                ('spotCash', models.DecimalField(decimal_places=2, default=50000, max_digits=20, verbose_name='\u73b0\u8d27\u8d44\u91d1')),
                ('vip', models.BooleanField(default=False, verbose_name='\u5927\u5ba2\u6237')),
                ('honest', models.BooleanField(default=True, verbose_name='\u8bda\u4fe1\u5ba2\u6237')),
                ('message', models.CharField(default='', max_length=30, verbose_name='\u8bf4\u660e')),
                ('status', models.IntegerField(default=0, verbose_name='\u72b6\u6001')),
                ('receivable', models.IntegerField(default=0, verbose_name='\u76c8\u5229\u603b\u989d')),
                ('first_trade_cash', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='\u9996\u7b14\u8d44\u91d1')),
                ('first_trade', models.DateTimeField(null=True, verbose_name='\u9996\u5355\u65f6\u95f4')),
                ('create', models.DateTimeField(default=datetime.datetime(2016, 10, 17, 19, 12, 18, 716000), verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modify', models.DateTimeField(default=datetime.datetime(2016, 10, 17, 19, 12, 18, 716000), verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('bursar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bursar.Bursar')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Sale')),
                ('salesqq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wxqq.Qq')),
                ('saleswx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wxqq.Wx')),
                ('spotTeacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.SpotTeacher')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher')),
            ],
        ),
    ]
