# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-17 19:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='create',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 17, 19, 23, 11, 114000), verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='modify',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 17, 19, 23, 11, 114000), verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
    ]
