# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-20 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20161018_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='spotMessage',
            field=models.CharField(default='', max_length=100, verbose_name='\u73b0\u8d27\u5907\u6ce8'),
        ),
    ]
