# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-25 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customer_spotmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bursar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bursar.Bursar'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sale.Sale'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='salesqq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wxqq.Qq'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='saleswx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wxqq.Wx'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='spotTeacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.SpotTeacher'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.Teacher'),
        ),
    ]
