# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-17 19:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=30, unique=True)),
                ('role_desc', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmission', models.CharField(max_length=300)),
                ('checked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserCommitHis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('delta', models.IntegerField(default=0, verbose_name='\u53d8\u5316\u91cf')),
                ('total', models.IntegerField(default=0, verbose_name='\u603b\u91cf')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGradeHis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('delta', models.IntegerField(default=0, verbose_name='\u53d8\u5316\u91cf')),
                ('total', models.IntegerField(default=0, verbose_name='\u603b\u91cf')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u516c\u53f8')),
                ('commit', models.IntegerField(default=0, verbose_name='\u63d0\u4ea4\u6570')),
                ('grade', models.IntegerField(default=0, verbose_name='\u6709\u6548\u5ba2\u6237\u6570')),
                ('department', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u90e8\u95e8')),
                ('cid', models.CharField(blank=True, max_length=18, null=True, verbose_name='\u8eab\u4efd\u8bc1\u53f7')),
                ('nick', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u771f\u5b9e\u59d3\u540d')),
                ('failcount', models.IntegerField(default=-1, verbose_name='\u5931\u8d25\u6b21\u6570')),
                ('faillocktime', models.DateTimeField(null=True, verbose_name='\u5931\u8d25\u9501\u5b9a\u65f6\u95f4')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super.Title')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='usergradehis',
            unique_together=set([('user', 'day')]),
        ),
        migrations.AlterUniqueTogether(
            name='usercommithis',
            unique_together=set([('user', 'day')]),
        ),
    ]
