# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-21 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0002_auto_20161018_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='group',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='\u7ec4'),
        ),
    ]
