# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-18 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0004_auto_20161018_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(verbose_name='\u4ea4\u6613\u65f6\u95f4')),
                ('type', models.IntegerField(default=0, verbose_name='\u4ea4\u6613\u52a8\u4f5c')),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='\u91d1\u989d')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
        ),
    ]
