# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-24 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='\u76c8\u4e8f'),
        ),
        migrations.AddField(
            model_name='spot',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='\u624b\u7eed\u8d39'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='\u51c0\u5165\u91d1'),
        ),
    ]
