# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-18 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20161017_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='create',
            field=models.DateTimeField(verbose_name='\u4ea4\u6613\u65f6\u95f4'),
        ),
    ]
