# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-19 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_auto_20161018_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='paycash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='\u6536\u6b3e\u91d1\u989d'),
        ),
    ]
