# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-21 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        ('trade', '0006_trade_paycash'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.Stock'),
        ),
    ]
