# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-21 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_trade_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='stockid',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u4ea7\u54c1ID'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='stockname',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u4ea7\u54c1\u540d\u79f0'),
        ),
    ]
