# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-17 19:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qqid', models.CharField(max_length=30, unique=True, verbose_name='qq\u53f7')),
                ('password', models.CharField(default='', max_length=30, verbose_name='\u5bc6\u7801')),
                ('qqname', models.CharField(max_length=30, verbose_name='qq\u6635\u79f0')),
                ('friend', models.IntegerField(default=0, verbose_name='\u597d\u53cb\u6570')),
                ('modify', models.DateField(null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('create', models.DateField(null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('delete', models.DateField(null=True, verbose_name='\u5931\u6548\u65f6\u95f4')),
                ('reason', models.CharField(default='', max_length=30, verbose_name='\u5220\u9664\u7406\u7531')),
                ('bindsale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.Sale')),
            ],
        ),
        migrations.CreateModel(
            name='QqFriendHis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('delta', models.IntegerField(default=0, verbose_name='\u53d8\u5316\u91cf')),
                ('total', models.IntegerField(default=0, verbose_name='\u603b\u91cf')),
                ('qq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wxqq.Qq')),
            ],
        ),
        migrations.CreateModel(
            name='Wx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wxid', models.CharField(max_length=30, unique=True, verbose_name='\u5fae\u4fe1\u53f7')),
                ('password', models.CharField(default='', max_length=30, verbose_name='\u5bc6\u7801')),
                ('wxname', models.CharField(max_length=30, verbose_name='\u5fae\u4fe1\u6635\u79f0')),
                ('friend', models.IntegerField(default=0, verbose_name='\u597d\u53cb\u6570')),
                ('bindphone', models.CharField(default='', max_length=30, verbose_name='\u7ed1\u5b9a\u624b\u673a')),
                ('bindemail', models.CharField(default='', max_length=30, verbose_name='\u7ed1\u5b9a\u90ae\u4ef6')),
                ('bindqq', models.CharField(default='', max_length=30, verbose_name='\u7ed1\u5b9aQQ')),
                ('modify', models.DateField(null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('create', models.DateField(default=datetime.date(2016, 10, 17), verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('delete', models.DateField(null=True, verbose_name='\u5931\u6548\u65f6\u95f4')),
                ('reason', models.CharField(default='', max_length=30, verbose_name='\u5220\u9664\u7406\u7531')),
                ('bindsale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.Sale')),
            ],
        ),
        migrations.CreateModel(
            name='WxFriendHis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('delta', models.IntegerField(default=0, verbose_name='\u53d8\u5316\u91cf')),
                ('total', models.IntegerField(default=0, verbose_name='\u603b\u91cf')),
                ('wx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wxqq.Wx')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='wxfriendhis',
            unique_together=set([('wx', 'day')]),
        ),
        migrations.AlterUniqueTogether(
            name='qqfriendhis',
            unique_together=set([('qq', 'day')]),
        ),
    ]
