# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-18 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxqq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wx',
            name='create',
            field=models.DateField(verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
