# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-19 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxqq', '0002_auto_20161018_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='qq',
            name='protect',
            field=models.CharField(default='', max_length=30, verbose_name='\u5bc6\u7801'),
        ),
    ]
