# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-03 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxqq', '0003_qq_protect'),
    ]

    operations = [
        migrations.AddField(
            model_name='qq',
            name='company',
            field=models.CharField(default='', max_length=30, verbose_name='\u6240\u5c5e\u516c\u53f8'),
        ),
        migrations.AddField(
            model_name='wx',
            name='company',
            field=models.CharField(default='', max_length=30, verbose_name='\u6240\u5c5e\u516c\u53f8'),
        ),
        migrations.AlterField(
            model_name='wx',
            name='create',
            field=models.DateField(null=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
