# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-25 14:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bursar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bursar',
            name='binduser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
